### ISSUE TITLE
Not open direct in my pc

### ISSUE THREAD

**Issue by Arifaajiz** [ELHARAKA/MassPrivatekeysToWIF#1]
File is not open in my pc what problem I couldn't find it.
when I click on"pvkmassconvert_compressed.py" not open any thing just show all programs in open it. I mean shown notepad windows media player internet explorer all programs choose one of these program to open this file I,m a bigner my system is 32 bit windows 7 ultimate

**Comment by ELHARAKA** [comment]
Install Python2 or Python3.
