### ISSUE TITLE
No module named 'base58

### ISSUE THREAD

**Issue by fREAK1167** [ELHARAKA/MassPrivatekeysToWIF#2]
Exception has occurred: ModuleNotFoundError
No module named 'base58'
  File "C:\Users\Rus\AppData\Local\Temp\Rar$DIa0.578\pvkmassconvert_compressed.py", line 1, in <module>
    import binascii, hashlib, base58, sys

**Comment by ELHARAKA** [comment]
You are missing bitcoinlib, you can install it with:

Python2:

1) `pip install base58`
2) `pip install python_bitcoinlib`

Python3:

1) `python3 -m pip install base58`
2) `python3 -m pip install python_bitcoinlib`
