### ISSUE TITLE
WIF Private Keys to Decimal Format

### ISSUE THREAD

**Issue by agoora** [ELHARAKA/MassPrivatekeysToWIF#3]
Please tell me how to convert a list of WIF Private Keys to Decimal Format?
"5KGiKepuPy428uqfPy8qKgnyREbXepfb8ywXKQs7Pzxtxcpbndm" to
"0c28fca386c7a227600b2fe50b7cae11ec86d3bf1fbe471be89827e19d72aa1d"
Thanks.

**Comment by ELHARAKA** [comment]
https://github.com/PawelGorny/WifSolver

**Comment by ELHARAKA** [comment]
The tool now supports converting WIF Private Keys to Decimal Format. Just use the `pvkwif2hex.py` file for this functionality. Check the updated README for usage instructions.
