### ISSUE TITLE
missing WIF CHARACTERS

### ISSUE THREAD

**Issue by Handsomekaizer** [ELHARAKA/MassPrivatekeysToWIF#4]
Hello sir
Sorry to bother I was just going through your repo to see if you could help me. The problem I have is with my wallet private key characters, I mistakenly damaged the piece of paper I wrote it on, so I was wondering if you could help me write a program that will brute Force all the 10 missing characters very fast and find the correct characters and in return I will make a donation of 2 BTC to you if I find the correct keys

**Comment by ELHARAKA** [comment]
Hi, just to be honest thats too many missing characters. most (if not all) tools out there might only recover the private key which has missing 1-5 characters.

BUT, you might try this tool [](https://github.com/Coding-Enthusiast/FinderOuter) and hopefully it can help you recover your missing characters.

Cheers 🥂 .
