### ISSUE TITLE
Parenthesis error

### ISSUE THREAD

**Issue by ghost3666** [ELHARAKA/MassPrivatekeysToWIF#5]
The error you're encountering is because you are using Python 2.x syntax for the print statement in a Python 3.x environment. In Python 3.x, print is a function, so you need to use parentheses. Here's the corrected code for that line:

Replace this line:

print str.strip(line)

with:

print(str.strip(line))

After making this change, your code should work in a Python 3.x environment.

**Comment by ELHARAKA** [comment]
> The error you're encountering is because you are using Python 2.x syntax for the print statement in a Python 3.x environment. In Python 3.x, print is a function, so you need to use parentheses. Here's the corrected code for that line:
> 
> 
> 
> Replace this line:
> 
> 
> 
> print str.strip(line)
> 
> 
> 
> with:
> 
> 
> 
> 
> 
> print(str.strip(line))
> 
> 
> 
> After making this change, your code should work in a Python 3.x environment. 
> 
> 
> 
> 

Instead of using ChatGPT for a quickfix when you run into a problem, better first read the code and readme.

**Comment by ghost3666** [comment]
i m not a developer so i don't know better option, those days are gone to read, Chatgpt is better option

**Comment by ELHARAKA** [comment]
ChatGPT is helpful but not foolproof.

**Comment by ghost3666** [comment]
but in this situation it helps also i have tried more than 30 scripts from
Github and every issue and errors i face, i solved through chatgpt
